import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Sale } from '../types';

export const generatePDF = (sale: Sale) => {
  const doc = new jsPDF();
  
  // Company header
  doc.setFontSize(20);
  doc.setTextColor(0, 188, 212); // Cyan color
  doc.text('StockFlow', 20, 25);
  
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text('Modern Stock Management System', 20, 35);
  
  // Receipt details
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text('Sales Receipt', 20, 55);
  
  doc.setFontSize(10);
  doc.text(`Receipt #: ${sale.id}`, 20, 70);
  doc.text(`Date: ${new Date(sale.timestamp).toLocaleDateString()}`, 20, 80);
  doc.text(`Time: ${new Date(sale.timestamp).toLocaleTimeString()}`, 20, 90);
  
  // Items table
  const tableData = sale.items.map(item => [
    item.productName,
    item.quantity.toString(),
    `$${item.unitPrice.toFixed(2)}`,
    `$${item.totalPrice.toFixed(2)}`
  ]);
  
  autoTable(doc, {
    startY: 100,
    head: [['Product', 'Quantity', 'Unit Price', 'Total']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [0, 188, 212], // Cyan color
      textColor: [255, 255, 255],
      fontSize: 10,
      fontStyle: 'bold'
    },
    bodyStyles: {
      fontSize: 9,
      textColor: [60, 60, 60]
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245]
    },
    margin: { left: 20, right: 20 },
  });
  
  // Total
  const finalY = (doc as any).lastAutoTable.finalY || 150;
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  
  // Add separator line
  doc.setLineWidth(0.5);
  doc.line(20, finalY + 10, 190, finalY + 10);
  
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.text(`Total Amount: $${sale.totalAmount.toFixed(2)}`, 20, finalY + 25);
  
  // Footer
  doc.setFontSize(8);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('Thank you for your business!', 20, finalY + 45);
  doc.text('Generated by StockFlow - Modern Stock Management', 20, finalY + 55);
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, finalY + 65);
  
  // Add a subtle border
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(1);
  doc.rect(10, 10, 190, 277); // A4 size border
  
  // Save the PDF
  doc.save(`receipt-${sale.id}.pdf`);
};